#!/usr/bin/env python3
"""Deterministically maintain Memory navigation and the sharded maintenance log."""

from __future__ import annotations

import argparse
import fcntl
import hashlib
import json
import os
import re
import unicodedata
from contextlib import contextmanager
from dataclasses import dataclass
from pathlib import Path


DEFAULT_VAULT = Path("/Users/shiba/Documents/Obsidian/Silicon Cortex/Codex Memory")
GENERATED_NOTICE = "<!-- Generated by codex-memory-maintainer/scripts/maintain_memory.py; do not edit this generated view. -->"
SHARD_NOTICE = "<!-- Canonical monthly log maintained by codex-memory-maintainer/scripts/maintain_memory.py; use the official helper instead of direct edits. -->"
BLOCK_START = "<!-- BEGIN GENERATED MEMORY NAVIGATION -->"
BLOCK_END = "<!-- END GENERATED MEMORY NAVIGATION -->"
ENTRY_RE = re.compile(r"(?m)^## \[(\d{4}-\d{2}-\d{2})\] ([^\n]+)$")
CURRENT_ENTRY_LIMIT = 10
CATALOG_PATH = "wiki/catalog/catalog.json"
CATALOG_INDEX_PATH = "wiki/catalog/_index.md"
DEFAULT_MAINTENANCE_LOCK = Path("/private/tmp/codex-memory-maintenance.lock")


@contextmanager
def exclusive_memory_maintenance_lock():
    """Prevent concurrent log/index read-modify-write transactions."""
    path = Path(os.environ.get("CODEX_MEMORY_MAINTENANCE_LOCK", DEFAULT_MAINTENANCE_LOCK.as_posix()))
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a+b") as stream:
        fcntl.flock(stream.fileno(), fcntl.LOCK_EX)
        try:
            yield
        finally:
            fcntl.flock(stream.fileno(), fcntl.LOCK_UN)


@dataclass(frozen=True)
class LogEntry:
    date: str
    heading: str
    text: str

    @property
    def month(self) -> str:
        return self.date[:7]


def parse_entries(text: str) -> list[LogEntry]:
    matches = list(ENTRY_RE.finditer(text))
    entries: list[LogEntry] = []
    for index, match in enumerate(matches):
        end = matches[index + 1].start() if index + 1 < len(matches) else len(text)
        body = text[match.start():end].rstrip() + "\n"
        entries.append(LogEntry(match.group(1), match.group(0), body))
    return entries


def entry_stream_sha256(entries: list[LogEntry]) -> str:
    payload = "\n".join(entry.text.rstrip() for entry in entries).encode("utf-8")
    return hashlib.sha256(payload).hexdigest()


def _frontmatter(text: str) -> dict[str, str]:
    if not text.startswith("---\n"):
        return {}
    end = text.find("\n---\n", 4)
    if end < 0:
        return {}
    result: dict[str, str] = {}
    for line in text[4:end].splitlines():
        if ":" in line:
            key, value = line.split(":", 1)
            result[key.strip()] = value.strip().strip('"\'')
    return result


def _title(text: str, fallback: str) -> str:
    match = re.search(r"(?m)^# (.+)$", text)
    return match.group(1).strip() if match else fallback


def _wiki_link(path: Path, root: Path) -> str:
    return path.relative_to(root / "wiki").with_suffix("").as_posix()


def render_source_index(root: Path) -> str:
    source_root = root / "wiki/sources"
    groups: dict[str, list[tuple[str, str, str, str]]] = {}
    names = {
        "conversations/chatgpt-daily": "ChatGPT 日报",
        "conversations/codex-daily": "Codex 日报",
        "reviews/weekly": "周度复盘",
        "docs": "架构文档",
        "travel": "旅行与地点综合",
    }
    for path in sorted(source_root.rglob("*.md")):
        if path.name == "_index.md":
            continue
        text = path.read_text(encoding="utf-8")
        meta = _frontmatter(text)
        relative_parent = path.relative_to(source_root).parent.as_posix()
        family = next((key for key in names if relative_parent == key or relative_parent.startswith(key + "/")), relative_parent)
        groups.setdefault(family, []).append(
            (
                meta.get("date", ""),
                _wiki_link(path, root),
                _title(text, path.stem),
                "/".join(filter(None, (meta.get("coverage", ""), meta.get("status", "")))),
            )
        )
    lines = ["# 来源索引", "", GENERATED_NOTICE, "", "本页是 source summary 文件的机械导航；来源解释与判断保留在各 source 页面。", ""]
    ordered_groups = sorted(groups, key=lambda key: (list(names).index(key) if key in names else 99, key))
    for family in ordered_groups:
        lines.extend([f"## {names.get(family, family)}", ""])
        for date, link, title, state in sorted(groups[family], key=lambda item: (item[0], item[1]), reverse=True):
            suffix = f" — `{state}`" if state else ""
            lines.append(f"- [[{link}|{title}]]{suffix}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_wiki_navigation(root: Path) -> str:
    excluded_prefixes = ("wiki/sources/", "wiki/logs/", "wiki/generated/")
    excluded_names = {"wiki/index.md", "wiki/log.md", "wiki/memory-system-health.md", "wiki/project-dashboard.md"}
    groups: dict[str, list[tuple[str, str]]] = {}
    for path in sorted((root / "wiki").rglob("*.md")):
        relative = path.relative_to(root).as_posix()
        if relative in excluded_names or relative.startswith(excluded_prefixes) or path.name == "_index.md":
            continue
        text = path.read_text(encoding="utf-8")
        if (root / CATALOG_PATH).is_file():
            catalog_entries = load_catalog(root).get("entries", [])
            if relative == "wiki/projects.md" and any(
                str(item.get("kind", "")).startswith("project") for item in catalog_entries
            ):
                text = render_catalog_compatibility(root, "project")
            elif relative == "wiki/decisions.md" and any(
                item.get("kind") == "decision" for item in catalog_entries
            ):
                text = render_catalog_compatibility(root, "decision")
        group = path.relative_to(root / "wiki").parts[0] if len(path.relative_to(root / "wiki").parts) > 1 else "核心页面"
        groups.setdefault(group, []).append((_wiki_link(path, root), _title(text, path.stem)))
    lines = ["# Wiki 机械导航", "", GENERATED_NOTICE, "", "本页只列路径与页面标题；内容优先级和阅读建议仍由 [[index|Wiki 索引]] 人工维护。", ""]
    for group in sorted(groups, key=lambda item: (item != "核心页面", item)):
        lines.extend([f"## {group}", ""])
        for link, title in sorted(groups[group]):
            lines.append(f"- [[{link}|{title}]]")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def load_catalog(root: Path) -> dict:
    path = root / CATALOG_PATH
    if not path.is_file():
        return {}
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict) or data.get("schema_version") != "1.0":
        raise ValueError(f"{CATALOG_PATH} must use schema_version 1.0")
    entries = data.get("entries")
    if not isinstance(entries, list):
        raise ValueError(f"{CATALOG_PATH}.entries must be an array")
    return data


def _catalog_link(locator: str) -> str:
    path, separator, anchor = locator.partition("#")
    if path.startswith("wiki/"):
        path = path[5:]
    return f"{path[:-3] if path.endswith('.md') else path}{separator}{anchor}"


def _catalog_title(entries: list[dict]) -> str:
    has_projects = any(str(item.get("kind", "")).startswith("project") for item in entries)
    has_decisions = any(item.get("kind") == "decision" for item in entries)
    if has_projects and has_decisions:
        return "项目与决策目录"
    if has_projects:
        return "项目目录"
    if has_decisions:
        return "决策目录"
    return "目录"


def render_catalog_index(root: Path) -> str:
    catalog = load_catalog(root)
    entries = catalog.get("entries", [])
    lines = [
        f"# {_catalog_title(entries)}",
        "",
        GENERATED_NOTICE,
        "",
        "本页只投影稳定 ID、标题与 canonical locator；正文与来源边界保留在 curated history 页面，Dashboard 当前字段仍由 registry 单独负责。",
        "",
    ]
    groups = (("project", "项目与项目背景"), ("decision", "决策"))
    for prefix, title in groups:
        selected = [item for item in entries if str(item.get("kind", "")).startswith(prefix)]
        if not selected:
            continue
        lines.extend([f"## {title}", ""])
        for item in selected:
            lines.append(
                f"- `{item['id']}` — [[{_catalog_link(item['canonical_locator'])}|{item['title']}]]"
            )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_catalog_compatibility(root: Path, kind: str) -> str:
    catalog = load_catalog(root)
    if kind == "project":
        title = "项目"
        catalog_label = "项目目录"
        intro = "此路径保留全部旧项目链接与标题锚点；正文已无损迁移到 catalog history。Dashboard 当前标题、分类、状态、摘要、人工路由与编辑只以 `project-dashboard-case-registry.json` 为准。"
        entries = [item for item in catalog.get("entries", []) if str(item.get("kind", "")).startswith("project")]
    else:
        title = "决策"
        catalog_label = "决策目录"
        intro = "此路径保留全部旧决策链接与标题锚点；完整、source-backed 正文已无损迁移到 catalog history。"
        entries = [item for item in catalog.get("entries", []) if item.get("kind") == "decision"]
    lines = [f"# {title}", "", GENERATED_NOTICE, "", intro, "", f"完整机械目录：[[catalog/_index|{catalog_label}]]。", ""]
    for item in entries:
        lines.extend(
            [
                f"## {item['legacy_heading']}",
                "",
                f"- stable ID：`{item['id']}`",
                f"- canonical history：[[{_catalog_link(item['canonical_locator'])}|读取完整正文]]",
            ]
        )
        registry_ref = item.get("registry_ref")
        if registry_ref:
            lines.append(
                f"- current Dashboard fields：`project-dashboard-case-registry.json` → `{registry_ref}`（本目录不复制 live state）"
            )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_shard(month: str, entries: list[LogEntry]) -> str:
    return "\n".join([
        f"# Wiki 维护日志 {month}", "", SHARD_NOTICE,
        "", "本月分片是维护日志的 canonical、lossless、倒序记录；只通过官方 helper 写入。", "",
        "\n".join(entry.text.rstrip() for entry in entries), "",
    ])


def render_log_index(entries: list[LogEntry]) -> str:
    months: dict[str, int] = {}
    for entry in entries:
        months[entry.month] = months.get(entry.month, 0) + 1
    lines = ["# Wiki 维护日志归档", "", GENERATED_NOTICE, "", "Canonical monthly shards，按月倒序。", ""]
    for month in sorted(months, reverse=True):
        year = month[:4]
        lines.append(f"- [[logs/{year}/{month}|{month}]] — {months[month]} entries")
    return "\n".join(lines) + "\n"


def render_compatibility_log(entries: list[LogEntry]) -> str:
    shown = entries[:CURRENT_ENTRY_LIMIT]
    newest = shown[0].date if shown else "none"
    oldest = shown[-1].date if shown else "none"
    return "\n".join([
        "# Wiki 维护日志", "", GENERATED_NOTICE, "",
        "此路径保留为兼容入口。完整、不可丢失的 canonical 历史位于 [[logs/_index|月度分片]]；新条目只通过官方 helper 写入。",
        f"当前窗口显示最新 {len(shown)} 条（{newest} → {oldest}），由 canonical shards 重建。", "",
        "\n".join(entry.text.rstrip() for entry in shown), "",
    ])


def _replace_block(text: str, block: str) -> str:
    rendered = f"{BLOCK_START}\n{block.rstrip()}\n{BLOCK_END}"
    pattern = re.compile(re.escape(BLOCK_START) + r".*?" + re.escape(BLOCK_END), re.S)
    if pattern.search(text):
        return pattern.sub(rendered, text)
    marker = "\n## 规则\n"
    if marker in text:
        return text.replace(marker, f"\n{rendered}\n{marker}", 1)
    return text.rstrip() + "\n\n" + rendered + "\n"


def render_root_index(root: Path) -> str:
    links = []
    if (root / CATALOG_PATH).is_file():
        links.append("- [[wiki/catalog/_index|项目与决策目录]]")
    links.extend(
        [
            "- [[wiki/generated/wiki-navigation|全 Wiki 路径索引]]",
            "- [[wiki/sources/_index|来源摘要索引]]",
            "- [[wiki/logs/_index|维护日志月度归档]]",
        ]
    )
    block = f"## 机械导航（生成）\n\n{GENERATED_NOTICE}\n\n" + "\n".join(links)
    return _replace_block((root / "_index.md").read_text(encoding="utf-8"), block)


def render_wiki_index(root: Path) -> str:
    links = []
    if (root / CATALOG_PATH).is_file():
        links.append("- [[catalog/_index|项目与决策目录]]")
    links.extend(
        [
            "- [[generated/wiki-navigation|全 Wiki 路径索引]]",
            "- [[sources/_index|来源摘要索引]]",
            "- [[logs/_index|维护日志月度归档]]",
        ]
    )
    block = f"## 机械导航（生成）\n\n{GENERATED_NOTICE}\n\n" + "\n".join(links)
    return _replace_block((root / "wiki/index.md").read_text(encoding="utf-8"), block)


def load_shard_entries(root: Path) -> list[LogEntry]:
    entries: list[LogEntry] = []
    for path in sorted((root / "wiki/logs").glob("[0-9][0-9][0-9][0-9]/[0-9][0-9][0-9][0-9]-[0-9][0-9].md"), reverse=True):
        entries.extend(parse_entries(path.read_text(encoding="utf-8")))
    return entries


def generated_targets(root: Path, entries: list[LogEntry], *, include_shards: bool) -> dict[Path, str]:
    targets = {
        root / "wiki/sources/_index.md": render_source_index(root),
        root / "wiki/generated/wiki-navigation.md": render_wiki_navigation(root),
        root / "wiki/logs/_index.md": render_log_index(entries),
        root / "wiki/log.md": render_compatibility_log(entries),
        root / "_index.md": render_root_index(root),
        root / "wiki/index.md": render_wiki_index(root),
    }
    if (root / CATALOG_PATH).is_file():
        catalog_entries = load_catalog(root).get("entries", [])
        targets[root / CATALOG_INDEX_PATH] = render_catalog_index(root)
        if any(str(item.get("kind", "")).startswith("project") for item in catalog_entries):
            targets[root / "wiki/projects.md"] = render_catalog_compatibility(root, "project")
        if any(item.get("kind") == "decision" for item in catalog_entries):
            targets[root / "wiki/decisions.md"] = render_catalog_compatibility(root, "decision")
    if include_shards:
        months: dict[str, list[LogEntry]] = {}
        for entry in entries:
            months.setdefault(entry.month, []).append(entry)
        for month, month_entries in months.items():
            targets[root / f"wiki/logs/{month[:4]}/{month}.md"] = render_shard(month, month_entries)
    return targets


def atomic_replace_many(targets: dict[Path, str]) -> None:
    staged: dict[Path, Path] = {}
    originals = {path: path.read_bytes() if path.exists() else None for path in targets}
    try:
        for path, text in targets.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            temp = path.with_name(f".{path.name}.{os.getpid()}.tmp")
            with temp.open("w", encoding="utf-8") as handle:
                handle.write(text)
                handle.flush()
                os.fsync(handle.fileno())
            staged[path] = temp
        replaced: list[Path] = []
        try:
            for path, temp in staged.items():
                os.replace(temp, path)
                replaced.append(path)
        except Exception:
            for path in reversed(replaced):
                original = originals[path]
                if original is None:
                    path.unlink(missing_ok=True)
                else:
                    restore = path.with_name(f".{path.name}.{os.getpid()}.restore")
                    restore.write_bytes(original)
                    os.replace(restore, path)
            raise
    finally:
        for temp in staged.values():
            temp.unlink(missing_ok=True)


def migrate_legacy_log(root: Path) -> list[LogEntry]:
    if load_shard_entries(root):
        raise RuntimeError("canonical log shards already exist; refusing a second legacy migration")
    entries = parse_entries((root / "wiki/log.md").read_text(encoding="utf-8"))
    if not entries:
        raise RuntimeError("legacy wiki/log.md contains no dated entries")
    atomic_replace_many(generated_targets(root, entries, include_shards=True))
    return entries


def insert_entry(root: Path, entry_text: str) -> bool:
    parsed = parse_entries(entry_text.strip() + "\n")
    if len(parsed) != 1 or parsed[0].text.rstrip() != entry_text.strip():
        raise ValueError("entry must contain exactly one `## [YYYY-MM-DD] type | title` section")
    entry = parsed[0]
    entries = load_shard_entries(root)
    if any(existing.text == entry.text for existing in entries):
        atomic_replace_many(generated_targets(root, entries, include_shards=True))
        return False
    entries.append(entry)
    entries.sort(key=lambda item: item.date, reverse=True)
    atomic_replace_many(generated_targets(root, entries, include_shards=True))
    return True


def update_catalog_section(root: Path, stable_id: str, section_text: str) -> bool:
    """Atomically replace one governed catalog section and its integrity hash."""
    existing_issues = catalog_issues(root)
    if existing_issues:
        raise RuntimeError("catalog must be healthy before update: " + "; ".join(existing_issues))
    catalog = load_catalog(root)
    matches = [item for item in catalog.get("entries", []) if item.get("id") == stable_id]
    if len(matches) != 1:
        raise ValueError(f"catalog ID must match exactly one entry: {stable_id}")
    entry = matches[0]
    kind = str(entry.get("kind") or "")
    marker_by_kind = {
        "project": (
            "<!-- BEGIN LOSSLESS LEGACY PROJECT SECTION -->\n",
            "<!-- END LOSSLESS LEGACY PROJECT SECTION -->",
        ),
        "decision": (
            "<!-- BEGIN LOSSLESS LEGACY DECISION SECTION -->\n",
            "<!-- END LOSSLESS LEGACY DECISION SECTION -->",
        ),
    }
    marker_key = "project" if kind.startswith("project") else kind
    if marker_key not in marker_by_kind:
        raise ValueError(f"unsupported catalog kind for section update: {kind}")

    normalized = unicodedata.normalize("NFC", section_text.replace("\r\n", "\n").replace("\r", "\n"))
    if not normalized.endswith("\n"):
        normalized += "\n"
    expected_heading = f"## {entry.get('legacy_heading', '')}\n"
    if not normalized.startswith(expected_heading):
        raise ValueError(f"section must start with the unchanged legacy heading: {expected_heading.strip()}")
    if len(re.findall(r"(?m)^## ", normalized)) != 1:
        raise ValueError("catalog section must contain exactly one H2 heading")

    locator = str(entry.get("canonical_locator") or "")
    page_path = root / locator
    page = page_path.read_text(encoding="utf-8")
    start_marker, end_marker = marker_by_kind[marker_key]
    try:
        start = page.index(start_marker) + len(start_marker)
        end = page.index(end_marker, start)
    except ValueError as exc:
        raise ValueError(f"catalog page is missing governed section markers: {locator}") from exc
    digest = hashlib.sha256(normalized.encode("utf-8")).hexdigest()
    updated_page = page[:start] + normalized + page[end:]
    hash_pattern = re.compile(r"(?m)^- source section SHA-256：`[0-9a-f]{64}`$")
    if len(hash_pattern.findall(updated_page)) != 1:
        raise ValueError(f"catalog page must contain exactly one section hash metadata line: {locator}")
    updated_page = hash_pattern.sub(f"- source section SHA-256：`{digest}`", updated_page)
    entry["source_section_sha256"] = digest
    updated_catalog = json.dumps(catalog, ensure_ascii=False, indent=2) + "\n"

    catalog_path = root / CATALOG_PATH
    if page_path.read_text(encoding="utf-8") == updated_page and catalog_path.read_text(encoding="utf-8") == updated_catalog:
        return False
    atomic_replace_many({page_path: updated_page, catalog_path: updated_catalog})
    return True


def replace_entry_text(root: Path, old: str, new: str) -> bool:
    entries = load_shard_entries(root)
    matches = [index for index, entry in enumerate(entries) if old in entry.text]
    if not matches:
        if any(new in entry.text for entry in entries):
            return False
        raise ValueError("old log text not found in canonical shards")
    if len(matches) != 1:
        raise ValueError(f"old log text matched {len(matches)} entries")
    index = matches[0]
    updated = entries[index].text.replace(old, new)
    parsed = parse_entries(updated)
    if len(parsed) != 1:
        raise ValueError("replacement changed the entry boundary")
    entries[index] = parsed[0]
    atomic_replace_many(generated_targets(root, entries, include_shards=True))
    return True


def generation_issues(root: Path) -> list[str]:
    issues: list[str] = []
    issues.extend(catalog_issues(root))
    entries = load_shard_entries(root)
    if not entries:
        compatibility = root / "wiki/log.md"
        migrated = (root / "wiki/logs").exists() or (
            compatibility.exists() and GENERATED_NOTICE in compatibility.read_text(encoding="utf-8")
        )
        return ["no canonical monthly log shards found"] if migrated else []
    if any(entries[index].date < entries[index + 1].date for index in range(len(entries) - 1)):
        issues.append("canonical log entries are not reverse chronological")
    seen: set[str] = set()
    for entry in entries:
        digest = hashlib.sha256(entry.text.encode("utf-8")).hexdigest()
        if digest in seen:
            issues.append(f"duplicate canonical log entry: {entry.heading}")
        seen.add(digest)
    for path in sorted((root / "wiki/logs").glob("[0-9][0-9][0-9][0-9]/[0-9][0-9][0-9][0-9]-[0-9][0-9].md")):
        month = path.stem
        shard_entries = parse_entries(path.read_text(encoding="utf-8"))
        if any(entry.month != month for entry in shard_entries):
            issues.append(f"{path.relative_to(root)} contains an entry outside {month}")
    expected = generated_targets(root, entries, include_shards=True)
    for path, text in expected.items():
        if not path.exists() or path.read_text(encoding="utf-8") != text:
            issues.append(f"generated artifact drift: {path.relative_to(root)}")
    return issues


def catalog_issues(root: Path) -> list[str]:
    if not (root / CATALOG_PATH).is_file():
        return []
    try:
        entries = load_catalog(root).get("entries", [])
    except (OSError, ValueError, json.JSONDecodeError) as error:
        return [f"invalid catalog: {error}"]
    issues: list[str] = []
    seen_ids: set[str] = set()
    seen_locators: set[str] = set()
    seen_aliases: set[tuple[str, str]] = set()
    markers = {
        "project": (
            "<!-- BEGIN LOSSLESS LEGACY PROJECT SECTION -->\n",
            "<!-- END LOSSLESS LEGACY PROJECT SECTION -->",
            "wiki/catalog/projects/",
        ),
        "decision": (
            "<!-- BEGIN LOSSLESS LEGACY DECISION SECTION -->\n",
            "<!-- END LOSSLESS LEGACY DECISION SECTION -->",
            "wiki/catalog/decisions/",
        ),
    }
    for item in entries:
        stable_id = item.get("id")
        kind = item.get("kind")
        locator = item.get("canonical_locator")
        digest = item.get("source_section_sha256")
        if not isinstance(stable_id, str) or not stable_id:
            issues.append("catalog entry missing stable ID")
        elif stable_id in seen_ids:
            issues.append(f"duplicate catalog stable ID: {stable_id}")
        else:
            seen_ids.add(stable_id)
        if kind not in markers:
            issues.append(f"catalog entry {stable_id!r} has unsupported kind: {kind!r}")
            continue
        start_marker, end_marker, expected_prefix = markers[kind]
        if not isinstance(locator, str) or not locator.startswith(expected_prefix) or not locator.endswith(".md"):
            issues.append(f"catalog entry {stable_id!r} has invalid canonical locator: {locator!r}")
            continue
        if locator in seen_locators:
            issues.append(f"duplicate catalog canonical locator: {locator}")
        seen_locators.add(locator)
        aliases = item.get("aliases")
        if not isinstance(aliases, list) or not aliases:
            issues.append(f"catalog entry {stable_id!r} has no aliases")
        else:
            for alias in aliases:
                if not isinstance(alias, dict) or not isinstance(alias.get("type"), str) or not isinstance(alias.get("value"), str):
                    issues.append(f"catalog entry {stable_id!r} has invalid alias")
                    continue
                key = (alias["type"], alias["value"])
                if key in seen_aliases:
                    issues.append(f"duplicate catalog alias: {key[0]}={key[1]}")
                seen_aliases.add(key)
        if not isinstance(digest, str) or not re.fullmatch(r"[0-9a-f]{64}", digest):
            issues.append(f"catalog entry {stable_id!r} has invalid section hash")
            continue
        page_path = root / locator
        if not page_path.is_file():
            issues.append(f"catalog entry {stable_id!r} locator does not exist: {locator}")
            continue
        page = page_path.read_text(encoding="utf-8")
        try:
            start = page.index(start_marker) + len(start_marker)
            end = page.index(end_marker, start)
        except ValueError:
            issues.append(f"catalog entry {stable_id!r} is missing lossless section markers")
            continue
        normalized = unicodedata.normalize("NFC", page[start:end].replace("\r\n", "\n").replace("\r", "\n"))
        actual = hashlib.sha256(normalized.encode("utf-8")).hexdigest()
        if actual != digest:
            issues.append(f"catalog entry {stable_id!r} section hash mismatch")
    return issues


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=("migrate-log", "generate", "insert", "update-catalog-section"))
    parser.add_argument("--vault", type=Path, default=DEFAULT_VAULT)
    parser.add_argument("--entry-file", type=Path)
    parser.add_argument("--catalog-id")
    parser.add_argument("--section-file", type=Path)
    args = parser.parse_args()
    root = args.vault.expanduser().resolve()
    with exclusive_memory_maintenance_lock():
        if args.command == "migrate-log":
            entries = migrate_legacy_log(root)
            print(f"migrated {len(entries)} entries; sha256={entry_stream_sha256(entries)}")
        elif args.command == "generate":
            entries = load_shard_entries(root)
            if not entries:
                raise SystemExit("no canonical monthly log shards; run migrate-log first")
            atomic_replace_many(generated_targets(root, entries, include_shards=True))
            print(f"generated from {len(entries)} entries; sha256={entry_stream_sha256(entries)}")
        elif args.command == "insert":
            if not args.entry_file:
                raise SystemExit("insert requires --entry-file")
            changed = insert_entry(root, args.entry_file.read_text(encoding="utf-8"))
            print("inserted" if changed else "unchanged")
        else:
            if not args.catalog_id or not args.section_file:
                raise SystemExit("update-catalog-section requires --catalog-id and --section-file")
            changed = update_catalog_section(
                root,
                args.catalog_id,
                args.section_file.read_text(encoding="utf-8"),
            )
            print("updated" if changed else "unchanged")


if __name__ == "__main__":
    main()
